/**
 * Synthea FHIR Bundle Patient Parser
 * Ingests synthetic patient records generated by Synthea (https://github.com/synthetichealth/synthea)
 * and maps them into Avecinna's Inpatient and Outpatient schemas.
 */

export interface SyntheaPatientOutput {
  mrn: string;
  fullName: string;
  dateOfBirth: string;
  gender: string;
  patientType: 'INPATIENT' | 'OUTPATIENT';
  genotype: string;
  bloodGroup: string;
  allergies: string[];
  vitals: Record<string, any>;
  activeMedications: Array<{ name: string; dosage: string }>;
  clinicalNotes: Array<{ author: string; note: string; date: string }>;
}

export function parseSyntheaFhirBundle(fhirBundleJson: any): SyntheaPatientOutput {
  const entries = fhirBundleJson.entry || [];
  
  // 1. Extract Patient Resource
  const patientEntry = entries.find((e: any) => e.resource?.resourceType === 'Patient');
  const patientRes = patientEntry?.resource || {};

  const nameObj = patientRes.name?.[0] || {};
  const givenName = Array.isArray(nameObj.given) ? nameObj.given.join(' ') : nameObj.given || 'Synthetic';
  const familyName = nameObj.family || 'Patient';
  const fullName = `${givenName} ${familyName}`.trim();

  const gender = (patientRes.gender || 'MALE').toUpperCase();
  const dateOfBirth = patientRes.birthDate || '1990-01-01';
  
  // Extract MRN identifier
  const mrnIdentifier = patientRes.identifier?.find((i: any) => i.type?.text === 'Medical Record Number' || i.system?.includes('ssn') || i.value);
  const mrn = `MRN-SYN-${mrnIdentifier?.value || Math.floor(100000 + Math.random() * 900000)}`;

  // 2. Extract Allergies
  const allergies: string[] = [];
  entries.forEach((e: any) => {
    if (e.resource?.resourceType === 'AllergyIntolerance') {
      const allergyName = e.resource.code?.coding?.[0]?.display || e.resource.code?.text;
      if (allergyName) allergies.push(allergyName);
    }
  });

  // 3. Extract Observations (Vitals)
  const vitals: Record<string, any> = {
    bp: '120/80',
    hr: 72,
    spo2: 98,
    temp: 36.6,
  };

  entries.forEach((e: any) => {
    if (e.resource?.resourceType === 'Observation') {
      const code = e.resource.code?.coding?.[0]?.display || '';
      const val = e.resource.valueQuantity?.value;
      if (code.includes('Heart rate') && val) vitals.hr = Math.round(val);
      if (code.includes('Oxygen saturation') && val) vitals.spo2 = Math.round(val);
      if (code.includes('Body Temperature') && val) vitals.temp = Number(val.toFixed(1));
    }
  });

  // 4. Extract Medications
  const activeMedications: Array<{ name: string; dosage: string }> = [];
  entries.forEach((e: any) => {
    if (e.resource?.resourceType === 'MedicationRequest' || e.resource?.resourceType === 'MedicationStatement') {
      const medName = e.resource.medicationCodeableConcept?.coding?.[0]?.display || e.resource.medicationCodeableConcept?.text;
      if (medName) {
        activeMedications.push({
          name: medName,
          dosage: 'Standard Clinical Dose',
        });
      }
    }
  });

  // 5. Extract Clinical Notes & Conditions
  const clinicalNotes: Array<{ author: string; note: string; date: string }> = [];
  entries.forEach((e: any) => {
    if (e.resource?.resourceType === 'Condition') {
      const conditionName = e.resource.code?.coding?.[0]?.display || e.resource.code?.text;
      const date = e.resource.recordedDate || e.resource.onsetDateTime || new Date().toISOString();
      if (conditionName) {
        clinicalNotes.push({
          author: 'Attending Physician',
          note: `Diagnosed condition: ${conditionName}`,
          date,
        });
      }
    }
  });

  // Synthetic Genotype & Blood Group Assignment for Nigerian Context
  const genotypes = ['AA', 'AS', 'SS', 'AC'];
  const bloodGroups = ['O+', 'A+', 'B+', 'AB+', 'O-'];
  const genotype = genotypes[Math.floor(Math.random() * genotypes.length)];
  const bloodGroup = bloodGroups[Math.floor(Math.random() * bloodGroups.length)];

  return {
    mrn,
    fullName,
    dateOfBirth,
    gender,
    patientType: Math.random() > 0.3 ? 'INPATIENT' : 'OUTPATIENT',
    genotype,
    bloodGroup,
    allergies: allergies.length > 0 ? allergies : ['No Known Drug Allergies (NKDA)'],
    vitals,
    activeMedications: activeMedications.length > 0 ? activeMedications : [{ name: 'Paracetamol', dosage: '500mg' }],
    clinicalNotes: clinicalNotes.length > 0 ? clinicalNotes : [{ author: 'Triage Nurse', note: 'Routine patient assessment.', date: new Date().toISOString() }],
  };
}
